#ANN

In [ ]:
#Warning : Data pre processing is very rough

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('C-train.csv')

In [6]:
df

x1     x2     x3     x4     x5  y
0     3.29  13.54   9.40  12.62   1.95  B
1   -10.87  24.20  24.09  23.96   0.11  B
2   -20.62  32.28  32.31  33.47  -1.30  B
3     3.01   0.44  19.68  -8.05   2.38  A
4     7.53   2.31   4.71  -0.88   2.25  B
..     ...    ...    ...    ...    ... ..
185  -5.74 -11.02 -11.08  -8.11  -2.61  A
186   3.59   8.10   2.17   8.51   1.26  B
187  -5.97 -16.04  13.05 -24.04  -0.77  A
188 -41.36 -22.59 -18.71 -10.61 -12.06  C
189 -33.20 -24.31  -9.87 -18.42  -9.42  C

[190 rows x 6 columns]

In [7]:
df.describe()

x1          x2          x3          x4          x5
count  190.000000  190.000000  190.000000  190.000000  190.000000
mean    -4.140053   -2.780053    1.095211   -2.904158   -0.971684
std     15.743802   13.244920   16.433007   15.303813    3.985057
min    -41.360000  -29.760000  -51.640000  -38.460000  -12.060000
25%    -16.165000  -12.505000  -12.490000  -12.737500   -3.542500
50%     -5.940000   -3.265000    1.180000   -4.185000   -1.235000
75%      8.215000    4.250000   13.035000    7.315000    2.250000
max     32.940000   34.790000   51.240000   37.960000    7.320000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x1      190 non-null    float64
 1   x2      190 non-null    float64
 2   x3      190 non-null    float64
 3   x4      190 non-null    float64
 4   x5      190 non-null    float64
 5   y       190 non-null    object 
dtypes: float64(5), object(1)
memory usage: 9.0+ KB


In [9]:
for i in range(1,6):
  text = 'x' + str(i)
  low, high = df[text].quantile([0.05, 0.95])
  df.drop(df[df[text]<low].index,inplace=True)
  df.drop(df[df[text]>high].index,inplace=True)

In [10]:
df

x1     x2     x3     x4    x5  y
0     3.29  13.54   9.40  12.62  1.95  B
3     3.01   0.44  19.68  -8.05  2.38  A
4     7.53   2.31   4.71  -0.88  2.25  B
7     8.81 -13.08 -16.84 -12.19  0.32  A
8    10.51   2.69  13.65  -4.72  3.73  A
..     ...    ...    ...    ...   ... ..
177 -18.05   2.08 -13.57  12.69 -5.38  B
180  14.76 -13.46 -11.93 -16.16  2.14  A
182   8.49  12.75  12.80   8.92  3.45  B
185  -5.74 -11.02 -11.08  -8.11 -2.61  A
186   3.59   8.10   2.17   8.51  1.26  B

[108 rows x 6 columns]

In [11]:
X = df.drop('y',axis=1)

In [12]:
y = df['y']

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,random_state=100)

In [15]:
mlp = MLPClassifier(max_iter=1000)
mlp.fit(X_train,y_train)

MLPClassifier(max_iter=1000)

In [16]:
y_pred = mlp.predict(X_test)

In [17]:
print("Report")
print(classification_report(y_test,y_pred))
print("------------------")
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Report
              precision    recall  f1-score   support

           A       0.65      0.93      0.76        14
           B       0.75      0.60      0.67        15
           C       0.67      0.53      0.59        15

    accuracy                           0.68        44
   macro avg       0.69      0.69      0.67        44
weighted avg       0.69      0.68      0.67        44

------------------
Confusion Matrix
[[13  1  0]
 [ 2  9  4]
 [ 5  2  8]]


#Predict

In [18]:
df = pd.read_csv('C-test.csv')

In [19]:
df

x1     x2     x3     x4    x5     y
0  13.87  -1.59  -9.22  -1.92  2.49  D_01
1  39.41 -10.24   3.14 -24.40  9.37  D_02
2  -0.98  -6.98 -12.01  -3.83 -1.44  D_03
3  -4.39 -22.38   4.94 -29.28 -1.25  D_04
4  -8.66  -5.71  14.59 -10.83 -1.00  D_05
5   2.20   9.24  -5.77  13.47  0.30  D_06
6  -8.28  -5.53  20.95 -13.24 -0.36  D_07
7 -15.23  25.83  20.04  28.76 -1.23  D_08
8 -23.17 -18.72  -6.80 -15.12 -6.61  D_09
9  13.27  16.44   6.65  14.83  4.18  D_10

In [20]:
X = df.drop('y',axis=1)

In [21]:
y_pred = mlp.predict(X)

In [22]:
print(y_pred)

['A' 'A' 'A' 'C' 'C' 'B' 'A' 'B' 'C' 'B']
